Vagrant::Config.run do |config|
  config.vm.box_url = 'http://files.vagrantup.com/lucid32.box'
  config.vm.box = "lucid32"
  config.vm.provision :shell, :path => "bootstrap.rb"
  
  (1..2).each do |i|
    vmname = "slave#{i}"
    config.vm.define vmname.to_sym do |slave_conf|
      slave_conf.vm.host_name = vmname
      slave_conf.vm.network "33.33.66.#{i+100}"
      slave_conf.vm.provision :puppet_server
      slave_conf.vm.customize do |vm|
        vm.memory_size = 512
        vm.name = vmname
      end
    end
  end
    
  config.vm.define :master do |master_conf|
    master_conf.vm.host_name = "master"
    master_conf.vm.network "33.33.66.100"
    master_conf.vm.provision :puppet_server
    master_conf.vm.customize do |vm|
      vm.memory_size = 2048
      vm.name = "master"
    end
  end
end
